---

- name: 'install docker compose'
  become: yes
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
    dest: '/opt/bin/docker-compose'
    force: yes
    owner: root
    group: root
    mode: 0755

- name: 'is docker compose installed'
  shell: docker-compose --version
